services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-service-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      retries: 5
      start_period: 30s

  user-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
      - .env.docker
    environment:
      - IS_DOCKER=true
      - NODE_ENV=development # Set environment to development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - user-service-network

networks:
  user-service-network:
    driver: bridge

volumes:
  postgres_data:
