services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-8911023}
      POSTGRES_DB: ${DB_NAME:-creator_trends_user_service_docker}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-service-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-creator_trends_user_service_docker}" ]
      interval: 10s
      retries: 5
      start_period: 30s

  user-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=docker # Set to docker for Docker environment
      - LOG_DIR=/app/logs
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASS:-8911023}@db:5432/${DB_NAME:-creator_trends_user_service_docker}
    volumes:
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    networks:
      - user-service-network

networks:
  user-service-network:
    external: true

volumes:
  postgres_data:
