services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8911023
      POSTGRES_DB: creator_trends_user_service_docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-service-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d creator_trends_user_service_docker" ]
      interval: 10s
      retries: 5
      start_period: 30s

  user-service:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    ports:
      - "3001:3001"
    env_file:
      - .env
      - .env.docker
    environment:
      - IS_DOCKER=true
      - NODE_ENV=development
      - LOG_DIR=/app/logs
    volumes:
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    networks:
      - user-service-network

  test:
    build:
      context: ./
      dockerfile: Dockerfile
      target: test
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgres://postgres:8911023@db:5432/creator_trends_user_service_docker
    depends_on:
      db:
        condition: service_healthy
    networks:
      - user-service-network
    command: [ "npm", "run", "test:clean" ]

networks:
  user-service-network:
    driver: bridge

volumes:
  postgres_data: